name: Master Build

on:
  push:
    branches:
      - master

env:
  GITHUB_REF: ${{ github.ref }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE_PREFIX: turinginst/
  DIR_TO_BUILD: ./

jobs:
  build-env:
    env:
      IMAGE: bridge-data-env
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt-get update -y && sudo apt-get install -y apt-utils

    - name: Set Job Environment Variables
      run: |
        CALVER="$( date -u '+%Y.%m.%d' )"  # Calendar Versioning
        SHA="$( git rev-parse --short ${GITHUB_SHA} )"
        DOCKER_TAG="${CALVER}-${SHA}"
        IMAGE_NAME="${IMAGE_PREFIX}${IMAGE}"
        echo "::set-env name=DOCKER_TAG::${DOCKER_TAG}"
        echo "::set-env name=IMAGE_NAME::${IMAGE_NAME}"

    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install repo2docker
      run: |
        python3 -m pip install https://github.com/jupyter/repo2docker/archive/master.zip

    - name: Authenticate with Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Running repo2docker
      run: |
        if docker pull "${IMAGE_NAME}"; then
          echo "Using ${IMAGE_NAME} as cache"
          jupyter-repo2docker --image-name "${IMAGE_NAME}" --debug --no-run --push --user-id 1000 --user-name jovyan --cache-from "${IMAGE_NAME}" "${DIR_TO_BUILD}"
        else
          echo "Building ${IMAGE_NAME} from scratch"
          jupyter-repo2docker --image-name "${IMAGE_NAME}" --debug --no-run --push --user-id 1000 --user-name jovyan "${DIR_TO_BUILD}"
        fi

    - name: Tag and push image to Docker Hub
      run: |
        docker tag "${IMAGE_NAME}:latest" "${IMAGE_NAME}:${DOCKER_TAG}"
        docker push "${IMAGE_NAME}:${DOCKER_TAG}"
