name: Master Build

on:
  push:
    branches:
      - master
  pull_request:
    braches:
      - master

env:
  GITHUB_REF: ${{ github.ref }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE_PREFIX: sgibson91/
  DIR_TO_BUILD: environment

jobs:
  build-env:
    env:
      IMAGE: bridge-data-env
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set Job Environment Variables
      run: |
        CALVER="$( date -u '+%Y.%m.%d' )"  # Calendar Versioning
        SHA="$( git rev-parse --short ${GITHUB_SHA} )"
        DOCKER_TAG="${CALVER}-${SHA}"
        IMAGE_SPEC="${IMAGE_PREFIX}${IMAGE}:${DOCKER_TAG}"
        IMAGE_SPEC_LATEST="${IMAGE_PREFIX}${IMAGE}:latest"

        echo "::set-env name=DOCKER_TAG::${DOCKER_TAG}"
        echo "::set-env name=IMAGE_SPEC::${IMAGE_SPEC}"
        echo "::set-env name=IMAGE_SPEC_LATEST::${IMAGE_SPEC_LATEST}"

    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install repo2docker
      run: |
        python3 -m pip install https://github.com/jupyter/repo2docker/archive/master.zip

    - name: Authenticate with Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Running repo2docker
      run: |
        if docker pull "${IMAGE_SPEC_LATEST}"; then
          echo "Using ${IMAGE_SPEC_LATEST} as cache"
          jupyter-repo2docker --debug --user-name jovyan --user-id 1000 --no-run --image-name "${IMAGE_SPEC}" --cache-from "${IMAGE_SPEC_LATEST}" "${DIR_TO_BUILD}"
        else
          echo "Building ${IMAGE_SPEC} from scratch"
          jupyter-repo2docker --debug --user-name jovyan --user-id 1000 --no-run --image-name "${IMAGE_SPEC}" "${DIR_TO_BUILD}"
        fi
