name: repo2docker build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITHUB_REF: ${{ github.ref }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE_PREFIX: turinginst/
  DIR_TO_BUILD: ./

jobs:
  repo2docker:
    env:
      IMAGE: bridge-data-env
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get update -y && sudo apt-get install -y apt-utils

      - name: Set Job Environment Variables
        run: |
          CALVER="$( date -u '+%Y.%m.%d' )"  # Calendar Versioning
          SHA="$( git rev-parse --short ${GITHUB_SHA} )"
          DOCKER_TAG="${CALVER}-${SHA}"
          IMAGE_NAME="${IMAGE_PREFIX}${IMAGE}"
          echo "::set-env name=DOCKER_TAG::${DOCKER_TAG}"
          echo "::set-env name=IMAGE_NAME::${IMAGE_NAME}"

      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install repo2docker
        run: |
          python3 -m pip install \
          https://github.com/jupyter/repo2docker/archive/master.zip

      - name: Authenticate with Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login \
          -u ${{ secrets.DOCKER_USERNAME }} \
          --password-stdin

      - name: Docker pull previous build
        run: |
          docker pull ${IMAGE_NAME}

      - name: repo2docker build
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          repo2docker \
          --image-name "${IMAGE_NAME}" \
          --no-run \
          --push \
          --user-id 1000 \
          --user-name jovyan \
          --cache-from "${IMAGE_NAME}" \
          "${DIR_TO_BUILD}"

      - name: Tag and Push to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          docker tag "${IMAGE_NAME}:latest" "${IMAGE_NAME}:${DOCKER_TAG}"
          docker push "${IMAGE_NAME}:${DOCKER_TAG}"
      
      - name: Build and test repo2docker image
        if: github.event.pull_request
        run: |
          repo2docker --cache-from "${IMAGE_NAME}" "${DIR_TO_BUILD}" jupyter nbconvert --execute .tests/*.ipynb
